### ISSUE TITLE
Set up document

### ISSUE THREAD

**Issue by suyambuganesh** [velvia/FiloDB#8]
Is there any link\document, where I can find how to set up steps?

**Comment by velvia** [comment]
For now:  run "sbt test", which will set up all your Cassandra keyspaces
(it assumes Cassandra is in localhost:9042).  Then you should be able to
follow all the other README instructions.

On Mon, Aug 24, 2015 at 4:32 AM, suyambuganesh <notifications@github.com>
wrote:

> Is there any link\document, where I can find how to set up steps?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/velvia/FiloDB/issues/8>.
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by velvia** [comment]
I updated the README to say you need to install Cassandra first.

**Comment by suyambuganesh** [comment]
Thanks
